# Generated by Django 3.1.5 on 2021-01-22 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('Executive', 'Executive'), ('Campus', 'Campus'), ('Batch', 'Batch'), ('College', 'College')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['position__priority'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ONGOING', 'ongoing'), ('PAUSED', 'paused'), ('BLOCKED', 'blocked'), ('FINISHED', 'finished'), ('ARCHIVED', 'archived')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('base_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.baseposition')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('voter_batch', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.candidate')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.position')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.vote')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=3)),
                ('voting_status', models.BooleanField(default=True)),
                ('eligibility_status', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.campus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voter'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.campus'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.college'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.campus')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.college')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.candidate')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.issue')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.unit'),
        ),
        migrations.CreateModel(
            name='PollSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('ABSTAIN', 'abstain')], max_length=7)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.poll')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.vote')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.college')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.voter'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('base_position', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('position', 'party')},
        ),
    ]
